-- Criação da Stored Procedure Delete
CREATE PROCEDURE SP_D_FAR_FARMACIA(
@CODIGO INT) AS
SET NOCOUNT ON 
DECLARE @CODIGOFARMACIA INT

SELECT @CODIGOFARMACIA = COUNT (FAR_IN_CODIGO)
FROM FAR_FARMACIA
WHERE FAR_IN_CODIGO = @CODIGO

IF @CODIGOFARMACIA = 0 
BEGIN 
	RAISERROR('O CÓDIGO DO PRODUTO INFORMADO NÃO EXISTE!', 15,1)
	RETURN
END

DELETE FROM FAR_FARMACIA WHERE FAR_IN_CODIGO = @CODIGO
RETURN 
GO

-- O produto será deletado através do código
SP_D_FAR_FARMACIA 1

-- Saída de dados da tabela
SELECT * FROM FAR_FARMACIA