-- Criação da Stored Procedure Insert
CREATE PROCEDURE SP_I_FAR_FARMACIA(
@NOME VARCHAR(30), @QUANTIDADE VARCHAR(20), @MARCA VARCHAR(30), @FABRICANTE VARCHAR(30), @DESCRICAO VARCHAR(500), @PRECO NUMERIC(5,2))
AS
SET NOCOUNT ON
DECLARE @NOME_GERAL CHAR(7)

SELECT @NOME_GERAL = COUNT(FAR_ST_NOME) 
FROM 
	FAR_FARMACIA
WHERE 
	FAR_ST_NOME = @NOME

IF @NOME_GERAL > 0
BEGIN
	RAISERROR('O NOME DO PRODUTO JÁ EXISTE', 15,1)
	RETURN
END

IF @PRECO < 0
BEGIN
	RAISERROR('O VALOR DEVE SER IGUAL OU MAIOR QUE ZERO',15,1)
	RETURN
END

IF LEN(TRIM(@NOME ))= 0 OR LEN(TRIM(@MARCA)) = 0 OR LEN(TRIM(@FABRICANTE)) = 0 OR LEN(@PRECO) = 0
BEGIN
	RAISERROR('OS CAMPOS NOME, MARCA, FABRICANTE E PREÇO SÃO OBRIGATÓRIOS',15,1)
	RETURN
END
-- Chamando a função na Stored Procedure Insert
BEGIN
    DECLARE @SETVAL NUMERIC(5,2)
    SELECT dbo.FN_DESCONTO(@PRECO) AS 'NOVO VALOR COM DESCONTO'
END

INSERT INTO FAR_FARMACIA(FAR_ST_NOME, FAR_ST_QUANTIDADE, FAR_ST_MARCA, FAR_ST_FABRICANTE, FAR_ST_DESCRICAO, FAR_RE_PRECO) VALUES
(@NOME, @QUANTIDADE, @MARCA, @FABRICANTE, @DESCRICAO, dbo.FN_DESCONTO(@PRECO))
RETURN 

-- Teste da Stored Procedure Insert
SP_I_FAR_FARMACIA 'Ibuflex','8 Cápsulas','571','Legrand','Ibuflex contém ibuprofeno, que possui atividade analgésica, antitérmica e anti-inflamatória.', 25.00

-- Saída de dados da tabela
SELECT * FROM FAR_FARMACIA