-- Criação da Stored Procedure Select
CREATE PROCEDURE SP_S_FAR_FARMACIA
AS 
SELECT 
	FAR_IN_CODIGO 'CÓDIGO',
	FAR_ST_NOME AS 'NOME DO PRODUTO',
	FAR_ST_QUANTIDADE AS 'QUANTIDADE',
	FAR_ST_MARCA AS 'MARCA',
	FAR_ST_FABRICANTE AS 'FABRICANTE',
	TRIM(FAR_ST_DESCRICAO) AS 'DESCRIÇÃO',  
	FAR_DT_DATAINCLUSAO AS 'DATA DE INCLUSÃO',
	FAR_RE_PRECO AS 'PREÇO'
FROM
	FAR_FARMACIA
ORDER BY 
	FAR_IN_CODIGO
GO

-- Teste da Stored Procedure Select
SP_S_FAR_FARMACIA

--  Criação da busca por filtro
CREATE PROCEDURE SP_S_FAR_FARMACIA_NOME
@NOME VARCHAR(30)
AS
DECLARE @NOMEGERAL VARCHAR(30)
SELECT
	FAR_IN_CODIGO 'CÓDIGO',
	FAR_ST_NOME AS 'NOME DO PRODUTO',
	FAR_ST_QUANTIDADE AS 'QUANTIDADE',
	FAR_ST_MARCA AS 'MARCA',
	FAR_ST_FABRICANTE AS 'FABRICANTE',
	TRIM(FAR_ST_DESCRICAO) AS 'DESCRIÇÃO',  
	FAR_DT_DATAINCLUSAO AS 'DATA DE INCLUSÃO',
	FAR_RE_PRECO AS 'PREÇO'
FROM
	FAR_FARMACIA
WHERE
	FAR_ST_NOME = @NOME
ORDER BY
	FAR_ST_NOME

SELECT @NOMEGERAL = COUNT (FAR_ST_NOME)
FROM FAR_FARMACIA
WHERE FAR_ST_NOME = @NOME

IF @NOMEGERAL = 0 
BEGIN 
	RAISERROR('ESSE PRODUTO NÃO ESTÁ CADASTRADO!', 15,1)
	RETURN
END
GO

-- Teste da busca por filtro
SP_S_FAR_FARMACIA_NOME 'EPOCLER'

-- Saída de dados da tabela através da Stored Procedure
SP_S_FAR_FARMACIA