-- Criação da Stored Procedure de Update
CREATE PROCEDURE SP_U_FAR_FARMACIA(
@CODIGO INT, @NOME VARCHAR(30), @QUANTIDADE VARCHAR(20), @MARCA VARCHAR(30), @FABRICANTE VARCHAR(30), @DESCRICAO VARCHAR(500), @PRECO NUMERIC(5,2))
AS
SET NOCOUNT ON
DECLARE @CODIGO_GERAL INT

SELECT @CODIGO_GERAL = COUNT(FAR_IN_CODIGO) 
FROM 
	FAR_FARMACIA
WHERE 
	FAR_IN_CODIGO = @CODIGO

IF @CODIGO_GERAL = 0
BEGIN
	RAISERROR('O CÓDIGO DO PRODUTO NÃO EXISTE', 15,1)
	RETURN
END

IF @PRECO < 0
BEGIN
	RAISERROR('O VALOR DEVE SER IGUAL OU MAIOR QUE ZERO',15,1)
	RETURN
END

IF LEN(@CODIGO) = 0 OR LEN(TRIM(@NOME ))= 0 OR LEN(TRIM(@MARCA)) = 0 OR LEN(TRIM(@FABRICANTE)) = 0 OR LEN(@PRECO) = 0
BEGIN
	RAISERROR('OS CAMPOS NOME, MARCA, FABRICANTE E PREÇO SÃO OBRIGATÓRIOS',15,1)
	RETURN
END


UPDATE FAR_FARMACIA
SET
	FAR_ST_NOME = @NOME,
	FAR_ST_QUANTIDADE = @QUANTIDADE,
	FAR_ST_MARCA = @MARCA,
	FAR_ST_FABRICANTE = @FABRICANTE,
	FAR_ST_DESCRICAO = @DESCRICAO,
	FAR_RE_PRECO = @PRECO
WHERE
	FAR_IN_CODIGO = @CODIGO
RETURN
